version: "3.5"
networks:
  default:
    external:
      name: proxy
services:
  ck5:
    image: akilli/node
    container_name: ck5
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - source: .
        target: /app
        type: bind
